"""
Export utilities for RTL Schematics and FSM Diagrams.
Supports:
- Vector SVG (*.svg) via QSvgGenerator
- High-Resolution Raster PNG (*.png) with customizable DPI (ideal for LaTeX/Word reports)
"""
from __future__ import annotations

from PySide6.QtCore import QRectF, QSize, Qt
from PySide6.QtGui import QPainter, QImage, QColor
from PySide6.QtSvg import QSvgGenerator
from PySide6.QtWidgets import QGraphicsScene, QFileDialog, QMessageBox, QWidget


class DiagramExporter:
    @staticmethod
    def export_svg(scene: QGraphicsScene, parent: QWidget, default_name: str = "diagram.svg"):
        path, _ = QFileDialog.getSaveFileName(parent, "Exportar Diagrama como SVG", default_name, "Vector SVG (*.svg)")
        if not path:
            return

        rect = scene.itemsBoundingRect()
        if rect.isEmpty():
            QMessageBox.warning(parent, "Aviso", "El diagrama está vacío.")
            return

        # Add padding
        pad = 25.0
        rect.adjust(-pad, -pad, pad, pad)

        generator = QSvgGenerator()
        generator.setFileName(path)
        generator.setSize(QSize(int(rect.width()), int(rect.height())))
        generator.setViewBox(rect)
        generator.setTitle("ELO212 / IPD432 Schematic Diagram")
        generator.setDescription("Generated by IPD432 / ELO212 Digital Design Suite")

        painter = QPainter()
        if painter.begin(generator):
            painter.setRenderHint(QPainter.Antialiasing)
            painter.setRenderHint(QPainter.TextAntialiasing)
            # White background
            painter.fillRect(rect, QColor(255, 255, 255))
            scene.render(painter, rect, rect)
            painter.end()
            QMessageBox.information(parent, "Exportado", f"Diagrama SVG exportado exitosamente:\n{path}")
        else:
            QMessageBox.critical(parent, "Error", "No se pudo generar el archivo SVG.")

    @staticmethod
    def export_png(scene: QGraphicsScene, parent: QWidget, default_name: str = "diagram.png", dpi_scale: float = 2.0):
        path, _ = QFileDialog.getSaveFileName(parent, "Exportar Diagrama como PNG", default_name, "Imagen PNG (*.png)")
        if not path:
            return

        rect = scene.itemsBoundingRect()
        if rect.isEmpty():
            QMessageBox.warning(parent, "Aviso", "El diagrama está vacío.")
            return

        pad = 25.0
        rect.adjust(-pad, -pad, pad, pad)

        width = int(rect.width() * dpi_scale)
        height = int(rect.height() * dpi_scale)

        image = QImage(width, height, QImage.Format_ARGB32)
        image.fill(Qt.white)

        painter = QPainter(image)
        painter.setRenderHint(QPainter.Antialiasing)
        painter.setRenderHint(QPainter.TextAntialiasing)
        painter.setRenderHint(QPainter.SmoothPixmapTransform)

        target_rect = QRectF(0, 0, width, height)
        scene.render(painter, target_rect, rect)
        painter.end()

        if image.save(path, "PNG"):
            QMessageBox.information(parent, "Exportado", f"Diagrama PNG de alta resolución guardado en:\n{path}")
        else:
            QMessageBox.critical(parent, "Error", "No se pudo guardar la imagen PNG.")
